/* Approach #1 */
SELECT CITY, LENGTH(CITY) FROM STATION WHERE LENGTH(CITY) IN (SELECT MIN(LENGTH(CITY)) FROM STATION) ORDER BY CITY LIMIT 1;
SELECT CITY, LENGTH(CITY) FROM STATION WHERE LENGTH(CITY) IN (SELECT MAX(LENGTH(CITY)) FROM STATION) ORDER BY CITY LIMIT 1;

/* Approach #2 */
SELECT *
FROM (
    SELECT CITY, LENGTH(CITY) AS len
    FROM STATION
    ORDER BY LENGTH(CITY) ASC, CITY
    LIMIT 1
) AS SHORTEST
UNION ALL (
    SELECT CITY, LENGTH(CITY) AS len
    FROM STATION
    ORDER BY LENGTH(CITY) DESC, CITY
    LIMIT 1
);