/* Approach #1 */
SELECT CITY FROM (SELECT DISTINCT CITY FROM STATION 
WHERE (
  CITY LIKE 'A%' OR
  CITY LIKE 'E%' OR
  CITY LIKE 'I%' OR
  CITY LIKE 'O%' OR
  CITY LIKE 'U%')
) AS FIRST
WHERE (
  CITY LIKE '%A' OR
  CITY LIKE '%E' OR
  CITY LIKE '%I' OR
  CITY LIKE '%O' OR
  CITY LIKE '%U'
)

/* Approach #2 */
SELECT DISTINCT CITY
FROM STATION 
WHERE CITY REGEXP '^[aeiouAEIOU]' AND CITY REGEXP '[aeiouAEIOU]$' ORDER BY CITY;

